%YAML:1.0
trainDir: "../Documents/ml"
testDir: "../Documents/ml"
modelDir: "./generated_models"
logDir: "./log"
names: [ "loris", "thomas" ]
types: [ "yml", "HOG" ]
topologies: [
    "2_2",
    "2_2_2_2",
    "4_4_4",
    "4_4_4_4",
    "8_8",
    "8_8_8",
    "16_16",
    "8_16_32",
    "4_8_4",
    "26_4_26",
    "32_16_8",
    "26"
  ]